### ISSUE TITLE
Ember is not defined

### ISSUE THREAD

**Issue by kaermorchen** [pzuraq/tracked-maps-and-sets#21]
Hello.

Should this addon work without Ember's ecosystem? I tried and caught the error `Ember is not defined` on [this](https://github.com/pzuraq/tracked-maps-and-sets/blob/master/src/-private/util.ts#L38) line.

[demo](https://codesandbox.io/s/xenodochial-hermann-grnch?file=/src/index.js)

**Comment by kaermorchen** [comment]
Fixed in #28

**Comment by chriskrycho** [comment]
Fixed via #28. I'll cut a bug fix release shortly.
