### ISSUE TITLE
Ember 3.12 Support?

### ISSUE THREAD

**Issue by alexlafroscia** [pzuraq/tracked-maps-and-sets#6]
The README mentions that this addon is compatible with Ember 3.12, but the tests don't run against that version of Ember and, as far as I can tell from usage, it does not _actually_ work. Could you clarify whether it's intended that this addon works with Ember 3.12?

**Comment by chriskrycho** [comment]
Hey @alexlafroscia thanks for flagging this. I think that's just the default boilerplate from the version of Ember CLI with which @pzuraq generated this, and given it uses autotracking extensively I don't see how it *could* work with 3.12! I'll open a PR momentarily which resolves this by correcting that!
