### ISSUE TITLE
Deprecated use of Ember global

### ISSUE THREAD

**Issue by knownasilya** [pzuraq/tracked-maps-and-sets#80]
```
deprecate.js:136 DEPRECATION: Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead. [deprecation id: ember-global] See https://deprecations.emberjs.com/v3.x/#toc_ember-global for more details.
```

Looks like in consumeCollection. Saw deprecation through tracked-built-ins

**Comment by pzuraq** [comment]
`consumeCollection` is going to be removed in v2, we no longer need it on more recent versions of Ember (> 3.24)

**Comment by sandydoo** [comment]
@pzuraq, could we wrap this with a `!gte('3.24.0')` then?

https://github.com/pzuraq/tracked-maps-and-sets/blob/6261f88b5ecda5c594197b9bd21528d057d59ad5/src/-private/util.ts#L36-L43
